version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
    - ./src:/app/src
    - ./tsconfig.json:/app/tsconfig.json
    - ./package.json:/app/package.json

    user: "${UID}:${GID}"  
    environment:
      - NODE_ENV=development
